spring.application.name=hospital-api
server.port=8080

spring.datasource.url=jdbc:sqlite:../data/hospital.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.connection-init-sql=PRAGMA foreign_keys=ON

spring.sql.init.mode=never
